- hosts: localhost
  tasks:
  - name: copy deployment file
    copy:
      src: flask_deployment.yaml
      dest: /app
  - name: delete previous kubernetes objects
    command: kubectl delete -f /app/flask_deployment.yaml
  - name: Create deployment
    command: kubectl apply -f /app/flask_deployment.yaml
