- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy deployment file
    copy:
      src: flask_deployment.yaml
      dest: /ansible/
  - name: delete previous kubernetes objects
    command: kubectl delete -f /ansible/flask_deployment.yaml
  - name: Create deployment
    command: kubectl apply -f /ansible/flask_deployment.yaml
