- hosts: localhost
  tasks:
  - name: copy deployment file
    copy:
      src: flask_deployment.yaml
      dest: /usr/root/
  - name: delete previous kubernetes objects
    command: kubectl delete -f /usr/root/flask_deployment.yaml
  - name: Create deployment
    command: kubectl apply -f /usr/root/flask_deployment.yaml
