- hosts: localhost
  tasks:
  - name: copy deployment file
    copy:
      src: flask_deployment.yaml
      dest: 
  - name: delete previous kubernetes objects
    command: kubectl delete -f flask_deployment.yaml
  - name: Create deployment
    command: kubectl apply -f /flask_deployment.yaml
