- hosts: localhost
  gather_facts: no
  tasks:
   - name: Create Folder /app if not exist
     file:
      path: /root
      mode: 0755
      state: directory
  - name: copy deployment file
    copy:
      src: flask_deployment.yaml
      dest: /root/
  - name: delete previous kubernetes objects
    command: kubectl delete -f /root/flask_deployment.yaml
  - name: Create deployment
    command: kubectl apply -f /root/flask_deployment.yaml
