apiVersion: v1
kind: Service
metadata:
  name: flask-app-statefulset-service
  labels:
    app: flask-app
spec:
  ports:
    - port: 5001
  selector:
    app: flask-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app
spec:
  serviceName: "flask-app-statefulset-service"
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container-statefulset
          image: chaitanyathakur/flask_docker
          resources:
            limits:
              cpu: "250m"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 128Mi

          ports:
            - containerPort: 5001
          volumeMounts:
            - name: flaskapp
              mountPath: /home/thakur/pavotask/taskPavo/app

  volumeClaimTemplates:
    - metadata:
        name: flaskapp
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
